---
parser: babel-eslint

plugins:
- jsx-a11y
- prettier
- react
- react-hooks

extends:
- eslint:recommended
- plugin:jsx-a11y/strict
- plugin:react/recommended
  # Prettier configuration should be last, as per docs:
  # https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules
- prettier

parserOptions:
  ecmaVersion: 2015
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true
  node: true
  jest: true

settings:
  import/resolver:
    node:
      paths:
      - src

rules:
  # Core ESLint
  # Possible errors
  no-await-in-loop: error
  no-console: warn
  no-template-curly-in-string: error
  no-useless-backreference: error
  require-atomic-updates: error
  # Best practices
  accessor-pairs: error
  array-callback-return: error
  consistent-return: error
  curly: error
  default-case-last: error
  default-param-last: error
  dot-location: error, property
  dot-notation: error
  eqeqeq: error
  grouped-accessor-pairs: error
  guard-for-in: error
  no-alert: warn
  no-caller: error
  no-constructor-return: error
  no-empty-function: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-loop-func: error
  no-magic-numbers: warn, ignore: [0, -1, 1]
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  # TODO: Change warn to error in the next major version
  no-param-reassign: warn
  no-proto: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  no-void: error
  no-warning-comments: warn
  prefer-named-capture-group: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  radix: error, as-needed
  require-await: error
  # TODO: Change warn to error in the next major version
  require-unicode-regexp: warn
  wrap-iife: error, inside
  yoda: error, never, exceptRange: true
  # Variables
  no-shadow: error
  no-use-before-define: error, nofunc
  # Stylistic issues
  func-style: error, declaration, allowArrowFunctions: true
  # TODO: Change warn to error in the next major version
  one-var: warn, never
  # ECMAScript 6
  # TODO: Change warn to error in the next major version
  arrow-parens: warn, always
  no-confusing-arrow: error
  no-duplicate-imports: error, includeExports: true
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  # TODO: Change warn to error in the next major version
  object-shorthand: warn, always
  prefer-const: error
  prefer-destructuring:
  - error
  - { array:  false, object: true }
  - enforceForRenamedProperties: false
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  symbol-description: error

  # Import
  import/prefer-default-export: 'off'

  # Prettier
  prettier/prettier: warn

  # React
  react/jsx-filename-extension: 'off'
  react/jsx-wrap-multilines: 'off'

  # React hooks
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
