---
parser: babel-eslint

plugins:
- jsx-a11y
- prettier
- react
- react-hooks

extends:
- eslint:recommended
- plugin:jsx-a11y/strict
- plugin:react/recommended
  # Prettier configuration should be last, as per docs:
  # https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules
- prettier

parserOptions:
  ecmaVersion: 2015
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true
  node: true
  jest: true

settings:
  import/resolver:
    node:
      paths:
      - src

rules:
  # Core ESLint
  # Possible errors
  no-await-in-loop: error
  no-console: warn
  no-template-curly-in-string: warn
  no-useless-backreference: warn
  require-atomic-updates: warn
  # Best practices

  default-param-last: warn
  import/prefer-default-export: 'off'
  func-style:
  - error
  - declaration
  - allowArrowFunctions: true
  curly: error

  # Prettier
  prettier/prettier: warn

  # React
  react/jsx-filename-extension: 'off'
  react/jsx-wrap-multilines: 'off'

  # React hooks
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
