---
parser: babel-eslint

plugins:
- jsx-a11y
- prettier
- react
- react-hooks

extends:
- eslint:recommended
- plugin:jsx-a11y/strict
- plugin:react/recommended
- prettier

parserOptions:
  ecmaVersion: 2015
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true
  node: true
  jest: true

settings:
  import/resolver:
    node:
      paths:
      - src

rules:
  prettier/prettier: warn
  react/jsx-filename-extension: 'off'
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/jsx-wrap-multilines: 'off'
  default-param-last: warn
  import/prefer-default-export: 'off'
  func-style:
  - error
  - declaration
  - allowArrowFunctions: true
  curly: error
