name: Publish npm packages

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
        working-directory: ./packages/js-scripts
      - run: npm test
        working-directory: ./packages/js-scripts

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        working-directory: ./packages/js-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token_jsscripts}}
